dbt_poc:  # your profile name from dbt_project.yml
  target: dev  # your development environment
  outputs:
    
    dev:
      type: bigquery
      method: oauth
      project: my-gcp-dev-project  # name of the project in BigQuery
      dataset: dbt_poc_test  # your dataset for development (usually your name)
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
    
    prod: # your production environment
      type: bigquery
      method: oauth
      project: my-gcp-prod-project  # name of the project in BigQuery
      dataset: dbt_poc_prod  # your dataset for production
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
